<?php
namespace Bonaire\Admin\Includes;

use Exception;
use PHPMailer\PHPMailer\PHPMailer;
use Bonaire\Admin\Includes as AdminIncludes;
use WP_Error;
use WPCF7_ContactForm;

/**
 * If this file is called directly, abort.
 */
if ( ! defined( 'WPINC' ) ) {
	die;
}

/**
 * Include dependencies.
 */
if ( ! class_exists( 'PHPMailer\PHPMailer\PHPMailer' ) ) {
	include ABSPATH . 'wp-includes/PHPMailer/PHPMailer.php';
}
if ( ! class_exists( 'WPCF7_ContactForm' ) && file_exists( BONAIRE_PLUGINS_ROOT_DIR . 'contact-form-7/includes/contact-form.php' ) ) {
	include BONAIRE_PLUGINS_ROOT_DIR . 'contact-form-7/includes/contact-form.php';
}

/**
 * The class responsible for email functionality.
 *
 * @since             1.0.0
 * @package           bonaire
 * @subpackage        bonaire/admin/includes
 * @author            Demis Patti <demis@demispatti.ch>
 */
final class Bonaire_Settings_Evaluator extends PHPMailer {
	
	/**
	 * The domain of the plugin.
	 *
	 * @var      string $domain
	 * @since    0.9.6
	 * @access   protected
	 */
	protected $domain;
	
	/**
	 * Holds the instance of the class responsible for handling the user options.
	 *
	 * @var AdminIncludes\Bonaire_Options $Bonaire_Options
	 * @since    0.9.6
	 * @access   private
	 */
	private $Bonaire_Options;
	
	/**
	 * The class responsible for setting the account settings status.
	 *
	 * @var AdminIncludes\Bonaire_Settings_Status $Bonaire_Settings_Status
	 * @since    1.0.0
	 * @access   private
	 */
	private $Bonaire_Settings_Status;
	
	/**
	 * Holds the stored options.
	 *
	 * @var object $stored_options
	 * @since    0.9.6
	 * @access   private
	 */
	private $stored_options;
	
	/**
	 * Holds the options meta data.
	 *
	 * @var object $options_meta
	 * @since    0.9.6
	 * @access   private
	 */
	private $options_meta;
	
	/**
	 * Sets up an instance of the mailer class.
	 *
	 * @param null $exceptions
	 *
	 * @return PHPMailer $mail
	 * @since 0.9.6
	 */
	private function phpmailer( $exceptions = null ) {
		
		// Create Instance
		$mail = new parent;
		// Setup
		$mail->Host       = $this->stored_options->smtp_host;
		$mail->CharSet    = 'utf-8';
		$mail->SMTPAuth   = true;
		$mail->Port       = $this->stored_options->smtp_port;
		$mail->From       = $this->stored_options->from;
		$mail->FromName   = $this->stored_options->fromname;
		$mail->Username   = $this->stored_options->username;
		$mail->Password   = $this->decrypt( $this->stored_options->password );
		$mail->SMTPSecure = $this->stored_options->smtpsecure;
		$mail->SMTPAutoTLS = false;
		$mail->isSMTP();
		
		// Debug
		if ( null !== $exceptions ) {
			$mail->SMTPDebug   = 3;
			$mail->Debugoutput = function ( $str, $level ) {
				
				global $debug;
				$debug[] .= "$level: $str\n";
			};
			$mail->Timeout     = 5;
		}
		
		return $mail;
	}
	
	/**
	 * Decrypts the password for the email account stored for replies.
	 *
	 * @param string $string
	 *
	 * @return string $output|bool
	 * @since 0.9.6
	 * @see   \Bonaire\Admin\Includes\Bonaire_Options crypt()
	 */
	private function decrypt( $string ) {
		
		$secret_key = defined( AUTH_KEY ) ? AUTH_KEY : 'r4RWH*ynn!AS.|A-j<qph!#))@!Gde5i,0&Z[R=i.]78f[Ine)aChIMwRpqZN$6~';
		$secret_iv  = defined( AUTH_SALT ) ? AUTH_SALT : '=;.6h~xr5v/BZuKP-|GR B*Kb`K-Q@PH6r>My6=-gz$qTt+X!0Rc_6>N:&g5&1>R';
		
		if ( '' === $secret_key || '' === $secret_iv ) {
			return $string;
		}
		
		$encrypt_method = 'AES-256-CBC';
		$key            = hash( 'sha256', $secret_key );
		$iv             = substr( hash( 'sha256', $secret_iv ), 0, 16 );
		
		return openssl_decrypt( base64_decode( $string ), $encrypt_method, $key, 0, $iv );
	}
	
	/**
	 * Returns test mail data.
	 *
	 * @return object $data
	 * @since 0.9.6
	 */
	private function testmail_data() {
		
		$data           = (object) array();
		$data->subject  = __( 'Bonaire Testmail', $this->domain );
		$data->message  = __( 'Howdy. This test message was generated by "Bonaire" for WordPress. Thanks for using this plugin!', $this->domain );
		$data->from     = $this->stored_options->from;
		$data->fromname = $this->stored_options->fromname;
		
		return $data;
	}
	
	/**
	 * @since 1.0.0
	 */
	private function set_email_account_settings_evaluator() {
		
		$this->Bonaire_Settings_Status = new Bonaire_Settings_Status( $this->domain );
	}
	
	/**
	 * Bonaire_Account_Evaluator constructor.
	 *
	 * @param string $domain
	 * @param AdminIncludes\Bonaire_Options $Bonaire_Options
	 */
	public function __construct( $domain, $Bonaire_Options ) {
		
		parent::__construct();
		
		$this->domain          = $domain;
		$this->Bonaire_Options = $Bonaire_Options;
		$this->stored_options  = $Bonaire_Options->get_stored_options();
		$this->options_meta    = $Bonaire_Options->get_options_meta();
		$this->set_email_account_settings_evaluator();
	}
	
	/**
	 * Sets up the mailer instance.
	 *
	 * @param object $data
	 * @param string $recipient_email_address
	 * @param null $exceptions
	 *
	 * @return PHPMailer $mail
	 * @since 0.9.6
	 */
	private function setup( $data, $recipient_email_address, $exceptions = null ) {
		
		$mail = $this->phpmailer( $exceptions );
		$mail->AddAddress( $recipient_email_address );
		$mail->AddReplyTo( $this->stored_options->from );
		$mail->Subject  = strip_tags( $data->subject );
		$mail->Body     = strip_tags( $data->message );
		$mail->From     = $this->stored_options->from;
		$mail->FromName = $data->fromname;
		$mail->isSMTP();
		$mail->SMTPAutoTLS = false;
		
		return $mail;
	}
	
	/**
	 * Sends a test mail.
	 *
	 * @param string $recipient_email_address
	 *
	 * @return bool|\WP_Error
	 * @throws \Exception
	 * @since 0.9.6
	 */
	public function send_testmail( $recipient_email_address ) {
		
		$mail = $this->setup( $this->testmail_data(), $recipient_email_address, null );
		
		try {
			$result = $mail->Send();
		} catch( Exception $e ) {
			
			return new WP_Error( (string) $e->getCode(), (string) $e->getMessage() );
		}
		
		// If sending the test message failed
		if ( false === $result ) {
			$error_message = __( 'Sending test message failed:', $this->domain ) . ' ' . __( 'Could not reach the mail server.', $this->domain ) . '<br>' . __( 'Please make sure that you are connected to the internet, and that you\'ve tested the SMTP and IMAP settings with the respective buttons on this plugin\'s settings page.', $this->domain );
			
			return new WP_Error( - 2, $error_message );
		}
		
		return $result;
	}
	
	/**
	 * Returns an instance of the mailer class.
	 *
	 * @param null $exceptions
	 *
	 * @return \PHPMailer
	 * @since 0.9.6
	 */
	private function get_phpmailer( $exceptions = null ) {
		
		return $this->phpmailer( $exceptions );
	}
	
	/**
	 * Calls the method that evaluates the SMTP settings.
	 *
	 * @return bool|array|\WP_Error
	 * @throws \Exception
	 * @since 0.9.6
	 */
	public function bonaire_test_smtp_settings() {
		// Get the options from the database since this test runs after the user saves the settings.
		$this->stored_options = $this->Bonaire_Options->get_stored_options();
		
		return $this->test_smtp_settings();
	}
	
	/**
	 * Runs the routine that tests the contact form.
	 *
	 * @return bool|array|\WP_Error
	 * @throws \Exception
	 * @since 1.0.0
	 */
	private function test_contact_form_settings() {
		// Get the options from the database since this test runs after the user saves the settings.
		$result = $this->get_missing_settings_fields( 'contact_form' );
		if ( is_wp_error( $result ) ) {
			
			return $result;
		}
		
		$result = $this->test_form();
		if ( is_wp_error( $result ) ) {
			$status = 'orange';
			$error_code = $result->get_error_code();
			$error_code = isset( $error_code ) ? $error_code : false;
			$result = array(
				'success' => false,
				'message' => $result->get_error_message(),
				'messages' => false,
				'error_code' => $error_code
			);
			
			$this->Bonaire_Settings_Status->set_settings_status( 'cf7', $status );
			
			return $this->create_response( $result, $status );
		}
		
		if ( true === $result['success'] ) {
			$status = 'green';
			$this->Bonaire_Settings_Status->set_settings_status( 'cf7', $status );
		} else {
			$status = 'orange';
			$this->Bonaire_Settings_Status->set_settings_status( 'cf7', $status );
		}
		
		return $this->create_response( $result, $status );
	}
	
	/**
	 * Check if the form is filled out completely. If so, evaluate the SMTP settings.
	 * Sets the 'settings status' after evaluation.
	 *
	 * @return bool|array|\WP_Error
	 * @throws \Exception
	 * @since 0.9.6
	 */
	private function test_smtp_settings() {
		
		$result = $this->get_missing_settings_fields( 'smtp' );
		if( is_wp_error( $result ) ) {
		
			return $result;
		}
		
		$result = $this->evaluate_smtp_settings();
		if ( is_wp_error( $result ) ) {
			$status = 'orange';
			$error_code = $result->get_error_code();
			$error_code = isset( $error_code ) ? $error_code : false;
			$result = array(
				'success' => false,
				'message' => $result->get_error_message(),
				'messages' => false,
				'error_code' => $error_code
			);
			
			$this->Bonaire_Settings_Status->set_settings_status( 'smtp', $status );
			
			return $this->create_response( $result, $status );
		}
		
		$status = $this->Bonaire_Settings_Status->get_settings_status( 'smtp' );
		if ( true === $result['success'] ) {
			$this->Bonaire_Settings_Status->set_settings_status( 'smtp', 'green' );
		} else {
			$status = 'orange';
			$this->Bonaire_Settings_Status->set_settings_status( 'smtp', 'orange' );
		}
		
		return $this->create_response( $result, $status );
	}
	
	/**
	 * Calls the function that evaluates the IMAP settings.
	 *
	 * @return bool|array|\WP_Error
	 * @throws \Exception
	 * @since 0.9.6
	 */
	public function bonaire_test_imap_settings() {
		// Get the options from the database since this test runs after the user saves the settings.
		$this->stored_options = $this->Bonaire_Options->get_stored_options();
		
		return $this->test_imap_settings();
	}
	
	/**
	 * Runs a series of methods to evaluate the IMAP settings.
	 *
	 * @return bool|array|\WP_Error
	 * @throws \Exception
	 * @since 0.9.6
	 */
	private function test_imap_settings() {

		$result = $this->get_missing_settings_fields( 'smtp' );
		if ( is_wp_error( $result ) ) {
			
			return $result;
		}
		
		$result = $this->get_missing_settings_fields( 'imap' );
		if ( is_wp_error( $result ) ) {
			
			return $result;
		}

		if ( 'yes' === $this->stored_options->{0}->save_reply ) {
			$this->Bonaire_Settings_Status->set_settings_status( 'imap', 'orange' );
		} else {
			$this->Bonaire_Settings_Status->set_settings_status( 'imap', 'inactive' );
		}
		
		$result = $this->evaluate_imap_settings();
		if ( is_wp_error( $result ) ) {
			$status = 'orange';
			$error_code = $result->get_error_code();
			$error_code = isset( $error_code ) ? $error_code : false;
			$result = array(
				'success' => false,
				'message' => $result->get_error_message(),
				'messages' => false,
				'error_code' => $error_code
			);
			$this->Bonaire_Settings_Status->set_settings_status( 'imap', $status );
			
			return $this->create_response( $result, $status );
		}
		
		if ( true === $result['success'] ) {
			$status = 'green';
			$this->Bonaire_Settings_Status->set_settings_status( 'imap', $status );
		} else {
			$status = 'orange';
			$this->Bonaire_Settings_Status->set_settings_status( 'imap', $status );
		}
		
		return $this->create_response( $result, $status );
	}
	
	/**
	 * Checks if there are no empty input fields on the settings page.
	 *
	 * @param string $section
	 *
	 * @return array|WP_Error
	 * @since 1.0.0
	 */
	private function get_missing_settings_fields($section){

		$keys = $this->Bonaire_Options->{$section . '_hash_keys'};

		$result = array();
		foreach ( (array) $keys as $key => $value ) {
			if ( isset( $this->stored_options->{$key} ) && '' === $this->stored_options->{$key} ) {
				if ( 'inbox_folder_path' !== $key /*|| 'form_id' === $key && 'none' === $this->stored_options->{$key}*/ ) {
					$result[] = $this->options_meta->{$key}['name'];
				}
			}
		}
		
		if ( empty( $result ) ) {
			
			return $result;
		}
		
		if ( is_array( $result ) && 1 < count( $result ) ) {
			$string = implode( ', ', $result );
		} else {
			$string = $result[0];
		}
		
		$result = array(
			'success' => false,
			'message' => wp_sprintf( __( 'Please enter the account information for the following settings fields: %1$s.', $this->domain ), $string ),
			'messages' => false,
			'error_code' => 1
		);
		
		return $this->create_response( $result, 'orange' );
	}
	
	/**
	 * Calls the method that evaluates the SMTP settings.
	 *
	 * @return bool|array|WP_Error
	 * @throws \Exception
	 * @since 0.9.6
	 */
	public function evaluate_smtp_settings() {
		
		$stored_options = $this->Bonaire_Options->get_stored_options();
		$smtp_host      = $stored_options->smtp_host;
		$smtp_port      = $stored_options->smtp_port;
		$smtp_ports     = array( $stored_options->smtp_port );
		
		return $this->run_smtp_evaluation( $smtp_host, $smtp_port, $smtp_ports );
	}
	
	/**
	 * Runs a series of methods to evaluate the SMTP settings.
	 *
	 * @param string $smtp_host
	 * @param int $smtp_port
	 * @param array $smtp_ports
	 *
	 * @return array|WP_Error
	 * @throws \Exception
	 * @since 0.9.6
	 */
	private function run_smtp_evaluation( $smtp_host, $smtp_port, $smtp_ports ) {
		
		$mail = $this->get_phpmailer( true );
		$response = null;
		$messages = false;
		
		// Check Internet Connection
		$connection_result = $this->is_connected();
		if ( is_wp_error( $connection_result ) ) {
			$error_code = $connection_result->get_error_code();
			$error_code = isset( $error_code ) ? $error_code : false;
			$result     = array(
				'success' => false,
				'message' => $connection_result->get_error_message(),
				'messages' => $messages,
				'error_code' => $error_code
			);
			
			return $this->create_response( $result, 'orange' );
		}
		$messages[] = __( 'Successfully checked internet connection.', $this->domain );
		
		// Test SMTP user credentials
		$socket = fsockopen( $smtp_host, $smtp_port, $errno, $errstr, 2 );
		$credentials_result = $this->test_credentials( $mail );
		fclose( $socket );
		if ( is_wp_error( $credentials_result ) ) {
			$error_code = $credentials_result->get_error_code();
			$error_code = isset( $error_code ) ? $error_code : false;
			$result = array(
				'success' => false,
				'message' => $credentials_result->get_error_message(),
				'messages' => $messages,
				'error_code' => $error_code
			);
			
			return $this->create_response( $result, 'orange' );
		}
		$messages[] = __( 'Successfully authenticated to the email account via SMTP.', $this->domain );
		
		//Resolve SMTP hostname
		$resolve_result = $this->resolve_smtp_hostname( $smtp_host );
		if ( is_wp_error( $resolve_result ) ) {
			$error_code = $resolve_result->get_error_code();
			$error_code = isset( $error_code ) ? $error_code : false;
			$result     = array(
				'success' => false,
				'message' => $resolve_result->get_error_message(),
				'messages' => $messages,
				'error_code' => $error_code
			);
			
			return $this->create_response( $result, 'orange' );
		}
		$messages[] = __( 'Successfully resolved host name.', $this->domain );
		
		// Test SMTP port
		$port_result = $this->test_smtp_port( $smtp_host, $smtp_ports );
		if ( is_wp_error( $port_result ) ) {
			$error_code = $port_result->get_error_code();
			$error_code = isset( $error_code ) ? $error_code : false;
			$result     = array(
				'success' => false,
				'message' => $port_result->get_error_message(),
				'messages' => $messages,
				'error_code' => $error_code
			);
			
			return $this->create_response( $result, 'orange' );
		}
		$messages[] = __( 'Successfully tested SMTP port.', $this->domain );
		
		// Test SMTPSecure
		$smtpsecure_result = $this->test_connection_type($mail, 'smtp');
		if ( is_wp_error( $smtpsecure_result ) ) {
			$error_code = $smtpsecure_result->get_error_code();
			$error_code = isset( $error_code ) ? $error_code : false;
			$result     = array(
				'success' => false,
				'message' => $smtpsecure_result->get_error_message(),
				'messages' => $messages,
				'error_code' => $error_code
			);
			
			return $this->create_response( $result, 'orange' );
		}
		$messages[] = __( 'Successfully tested SMTPSecure setting.', $this->domain );
		
		// Add final success message.
		$messages[] = '<strong>' . __( 'Congratulations! Your SMTP settings are valid.', $this->domain ) . '</strong>';
		
		$result = array( 'success' => true, 'message' => false, 'messages' => $messages, 'error_code' => 0 );
		
		return $this->create_response( $result, 'green' );
	}
	
	/**
	 * Checks the contact form.
	 *
	 * @return array|bool|\WP_Error
	 * @throws \Exception
	 * @see test_form()
	 */
	public function bonaire_test_contact_form(){
		
		return $this->test_contact_form_settings();
	}
	
	/**
	 * Calls the method that evaluates the IMAP settings.
	 *
	 * @return array|WP_Error
	 * @throws \Exception
	 * @since 0.9.6
	 */
	public function evaluate_imap_settings() {

		return $this->run_imap_evaluation();
	}
	
	/**
	 * Evaluates the IMAP settings.
	 *
	 * @return array|WP_Error
	 * @throws \Exception
	 * @since 0.9.6
	 */
	private function run_imap_evaluation() {
		
		$imap_host  = $this->stored_options->imap_host;
		$imap_ports = array( $this->stored_options->imap_port );
		
		$mail = $this->get_phpmailer( true );
		$messages = false;
		$response = null;
		$wp_error = null;
		
		// Check Internet Connection
		$connection_result = $this->is_connected();
		if ( is_wp_error( $connection_result ) ) {
			$error_code = $connection_result->get_error_code();
			$error_code = isset( $error_code ) ? $error_code : false;
			$result     = array(
				'success' => false,
				'message' => $connection_result->get_error_message(),
				'messages' => $messages,
				'error_code' => $error_code
			);
			
			return $this->create_response( $result, 'orange' );
		}
		$messages[] = __( 'Successfully checked internet connection.', $this->domain );
		
		//Check for IMAP extension
		$extension_result = $this->is_imap_extension_loaded();
		if ( is_wp_error( $extension_result ) ) {
			$error_code = $extension_result->get_error_code();
			$error_code = isset( $error_code ) ? $error_code : false;
			$result     = array(
				'success' => false,
				'message' => $extension_result->get_error_message(),
				'messages' => $messages,
				'error_code' => $error_code
			);
			
			return $this->create_response( $result, 'orange' );
		}
		$messages[] = __( 'Successfully checked for IMAP extension.', $this->domain );
		
		//Resolve IMAP hostname
		$resolve_result = $this->resolve_imap_hostname( $imap_host );
		if ( is_wp_error( $resolve_result ) ) {
			$error_code = $resolve_result->get_error_code();
			$error_code = isset( $error_code ) ? $error_code : false;
			$result     = array(
				'success' => false,
				'message' => $resolve_result->get_error_message(),
				'messages' => $messages,
				'error_code' => $error_code
			);
			
			return $this->create_response( $result, 'orange' );
		}
		$messages[] = __( 'Successfully resolved host name.', $this->domain );
		
		// Test IMAP port
		$port_result = $this->test_imap_port( $imap_host, $imap_ports );
		if ( is_wp_error( $port_result ) ) {
			$error_code = $port_result->get_error_code();
			$error_code = isset( $error_code ) ? $error_code : false;
			$result     = array(
				'success' => false,
				'message' => $port_result->get_error_message(),
				'messages' => $messages,
				'error_code' => $error_code
			);
			
			return $this->create_response( $result, 'orange' );
		}
		$messages[] = __( 'Successfully tested IMAP port.', $this->domain );
		
		// Test SMTPSecure
		$smtpsecure_result = $this->test_connection_type( $mail, 'imap');
		if ( is_wp_error( $smtpsecure_result ) ) {
			$error_code = $smtpsecure_result->get_error_code();
			$error_code = isset( $error_code ) ? $error_code : false;
			$result     = array(
				'success' => false,
				'message' => $smtpsecure_result->get_error_message(),
				'messages' => $messages,
				'error_code' => $error_code
			);
			
			return $this->create_response( $result, 'orange' );
		}
		$messages[] = __( 'Successfully tested SMTPSecure setting.', $this->domain );
		
		// Test SSL
		if ( 'yes' === $this->stored_options->save_reply && 'cert' === $this->stored_options->ssl_certification_validation ) {
			
			$ssl_result = $this->is_ssl();
			if ( is_wp_error( $ssl_result ) ) {
				$error_code = $ssl_result->get_error_code();
				$error_code = isset( $error_code ) ? $error_code : false;
				$result     = array(
					'success' => false,
					'message' => $ssl_result->get_error_message(),
					'messages' => $messages,
					'error_code' => $error_code
				);
				
				return $this->create_response( $result, 'orange' );
			}
		}
		$messages[] = __( 'Successfully tested IMAP port.', $this->domain );
		
		// Test INBOX.Sent folder
		$folder_result = $this->test_inbox($mail);
		if ( is_wp_error( $folder_result ) ) {
			$error_code = $folder_result->get_error_code();
			$error_code = isset( $error_code ) ? $error_code : false;
			$result     = array(
				'success' => false,
				'message' => $folder_result->get_error_message(),
				'messages' => $messages,
				'error_code' => $error_code
			);
			
			return $this->create_response( $result, 'orange' );
		}
		$messages[] = __( 'Successfully contacted the inbox folder on the mail server.', $this->domain );
		
		// Add final success message.
		$messages[] = '<strong>' . __( 'Congratulations! Your IMAP settings are valid.', $this->domain ) . '</strong>';
		
		$result = array( 'success' => true, 'message' => false, 'messages' => $messages, 'error_code' => 0 );
		
		return $this->create_response( $result, 'green' );
	}
	
	/**
	 * @param array $result
	 * @param string $status
	 *
	 * @return array|WP_Error
	 */
	private function create_response( $result, $status ) {
		
		$string = '';
		$messages = isset( $result['messages'] ) && is_array($result['messages']) ? $result['messages'] : false;
		
		if ( isset( $messages ) && false !== $messages ) {
			foreach ( $result['messages'] as $i => $message ) {
				$string .= $message . '<br>';
			}
			$message = $string . '<br>' . $result['message'];
		} else {
			$message = $result['message'];
		}
		
		if ( true === $result['success'] ) {
			
			return array( 'success' => true, 'message' => $message, 'status' => $status );
		}
		
		return new WP_Error( $result['error_code'], $message, $status );
	}
	
	/**
	 * Checks if a contact form is set,
	 * is given the required form tags and has named them propperly.
	 *
	 * @return array|WP_Error
	 * @since 1.0.0
	 */
	private function test_form() {
		
		// Get the channel (a.k.a. form id)
		$channel = is_int( (int)str_replace( '_', '', $this->stored_options->channel )) ? (int) str_replace( '_', '', $this->stored_options->channel ) : false;
		// Check if there is a contact form we can use
		if(false === $channel || 0 === $channel){
			$error_message = '<strong>' . __( 'There\'s no contact form set yet.', $this->domain ) . '</strong><br>' . __( 'Please create / select your contact form first.', $this->domain );
			
			return new WP_Error( 1, $error_message );
		}
		// Add the channel to the args array
		$args = array(
			'id' => $channel,
			'post_status' => 'any',
			'posts_per_page' => -1,
			'orderby' => 'name',
			'order' => 'ASC',
		);
		// Get the contact form
		$contact_forms_by_channel = WPCF7_ContactForm::find( $args );
		/**
		 * @var WPCF7_ContactForm $contact_form
		 */
		$contact_form = null;
		foreach( $contact_forms_by_channel as $i => $cform){
			if($channel === $cform->id){
				$contact_form = $cform;
			}
		}
		// Extract the form tags
		$scanned_form_tags = $contact_form->scan_form_tags();
		$scanned_tags = array();
		foreach ( $scanned_form_tags as $j => $form_tag ) {
			$scanned_tags[] = $scanned_form_tags[ $j ]->name;
		}
		
		$expected_form_tags = array('your-email', 'your-name', 'your-subject', 'your-message');
		
		$error_message = '<strong>' . __( 'Form tags to review:', $this->domain ) . '</strong><br>';
		$errors = 0;
		// Compare the tags
		foreach( $expected_form_tags as $i => $expected_form_tag){
			if ( ! in_array( $expected_form_tag, $scanned_tags ) ) {
				$error_message .= '<span>' . __('Expected Form Tag:', $this->domain) . ' '.$expected_form_tag . '</span><br>';
				$errors++;
			}
		}
		
		if(0 !== $errors){
			
			return new WP_Error( 1, $error_message );
		}
		
		return array( 'success' => true, 'message' => __('Congratulations! The Contact Form seems to be configured as required.', $this->domain), 'messages' => false, 'error_code' => 0 );
	}
	
	/**
	 * @return bool|WP_Error
	 */
	private function is_connected() {
		
		try {
			$connection = @fsockopen( "www.google.com", 80, $errno, $errstr, 2 );
			if ( $connection ) {
				$result = true;
				fclose( $connection );
				flush();
			} else {
				flush();
				$error_message = '<strong>' . __( 'It seems that you are not connected to the internet, or a firewall is blocking access to it.', $this->domain ) . '</strong><br>' . __( 'Please make sure that you are connected to the internet.', $this->domain );
				$result        = new WP_Error( 1, $error_message );
			}
			unset( $connection );
			
			return $result;
		} catch( Exception $error ) {
			$error_message = '<strong>' . __( 'Internal Error: Unable to check the SMTP port.', $this->domain ) . '</strong><br>' . __( 'Please try again later.', $this->domain );
			
			return new WP_Error( 2, $error_message );
		}
	}
	
	/**
	 * Resolves the SMTP host name.
	 *
	 * @param string $smtp_host
	 *
	 * @return bool|\WP_Error
	 * @since 0.9.6
	 */
	private function resolve_smtp_hostname( $smtp_host ) {
		
		$protocol = 'SMTP';
		
		try {
			$test_dns = gethostbyname( $smtp_host . '.' );
			
			if ( ! preg_match( '/\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/', $test_dns ) ) {
				$error_message = '<strong>' . wp_sprintf( __( 'Failed to resolve %1$s host name (%2$s).', $this->domain ), $protocol, $smtp_host ) . '</strong><br>' . __( 'Please review your settings and run the test again.', $this->domain );
				
				return new WP_Error( 1, $error_message );
			}
		} catch( Exception $e ) {
			$error_message = '<strong>' . wp_sprintf( __( 'Internal Error: Unable to resolve %1$s host name (%2$s).', $this->domain ), $protocol, $smtp_host ) . '</strong><br>' . __( 'Please review your settings and run the test again.', $this->domain );
			
			return new WP_Error( 2, $error_message );
		}
		
		return true;
	}
	
	/**
	 * Checks the settings for SMTPSecure or IMAPSecure respectively.
	 *
	 * @param PHPMailer $mail
	 * @param string $encryption
	 *
	 * @return bool|\WP_Error
	 */
	private function test_connection_type($mail, $encryption) {
		
		if( 'imap' === $encryption){
			
			try {
				$protocol = 'IMAP';
				$ssl_certification_validation = 'nocert' === $this->stored_options->ssl_certification_validation ? '/novalidate-cert' : '';
				$mailbox = $this->get_mailbox( $mail, $ssl_certification_validation, true, false);
				
				// Check IMAP connection
				$imapStream = imap_open( $mailbox, $mail->Username, $mail->Password, OP_READONLY ) or false;
				if ( false !== $imapStream ) {
					// Close connection
					imap_close( $imapStream );
					
					return true;
				} else {
					$last_error = imap_last_error();
					if( preg_match('/#11001/', $last_error)){
						
						return new WP_Error( 1, wp_sprintf( __( 'Please check your %1$s Host url (%2$s) and try again.', $this->domain ), $protocol, $this->stored_options->imap_host ) );
					}
					
					if ( preg_match( '/IMAP connection broken/', $last_error ) ) {
						
						$encryption = 'ssl' === $this->stored_options->imapsecure ? 'TLS' : 'SSL';
						return new WP_Error( 1, wp_sprintf( __( 'It seems you shoud set the value for %1$sSecure to "%2$s".', $this->domain ), $protocol, $encryption ) . ' ' . __('Please review your settings and run the test again.', $this->domain) );
					}
					
					return new WP_Error( 1, __('IMAP Error', $this->domain) . ': ' . imap_last_error() );
				}

			} catch( Exception $e ) {
				
				return new WP_Error( 2, __( 'Internal Error: Unable to check IMAPSecure settings.', $this->domain ) . '<br>' . __( 'Please try again later.', $this->domain ) );
			}
		}
		
		try {
			if($mail->smtpConnect()){
				
				return true;
			}
			
			$stored_SMTPSecure = $mail->SMTPSecure;
			$stored_smtp_port = $mail->Port;
			
			if('ssl' === $mail->SMTPSecure){
				$port = 465;
				$mail->Port = $port;
				
				if ( $mail->smtpConnect() ) {
					
					return new WP_Error( 1, wp_sprintf( __( 'Please set your SMTP Port to %1$s, save the settings and try again.', $this->domain ), $port ) );
				}
			} else {
				$port = 587;
				$mail->Port = $port;
				
				if ( $mail->smtpConnect() ) {
					
					return new WP_Error( 1, wp_sprintf( __( 'Please set your SMTP Port to %1$s, save the settings and try again.', $this->domain ), $port ) );
				}
			}

			return new WP_Error( 1, wp_sprintf( __( 'Please review your Password, the settings for SMTPSecure (%1$s) and SMTP Port (%2$s) and try again.', $this->domain ), $stored_SMTPSecure, $stored_smtp_port ) );

		} catch( Exception $e ) {
			
			return new WP_Error( 2, __( 'Internal Error: Unable to check SMTPSecure settings.', $this->domain ) . '<br>' . __( 'Please try again later.', $this->domain ) );
		}
	}
	
	/**
	 * Tests the SMTP port.
	 *
	 * @param string $smtp_host
	 * @param array $smtp_ports
	 *
	 * @return bool|\WP_Error
	 * @since 0.9.6
	 */
	private function test_smtp_port( $smtp_host, $smtp_ports ) {
		
		try {
			if ( $socket = fsockopen( $smtp_host, $smtp_ports[0], $errno, $errstr, 2 ) ) {
				fclose( $socket );
				flush();
				$result = true;
			} else {
				flush();
				$error_message = '<strong>' . __( 'The SMTP port number seems to be wrong.', $this->domain ) . '</strong><br>' . __( 'Please review your setting.', $this->domain );
				$result        = new WP_Error( 1, $error_message );
			}
			unset( $socket );
		} catch( Exception $error ) {
			$error_message = __( 'Internal Error: Unable to check the SMTP port.', $this->domain ) . '<br>' . __( 'Please try again later.', $this->domain );
			
			return new WP_Error( 2, $error_message );
		}
		
		return $result;
	}
	
	/**
	 * Tests the SMTP user credentials and settings.
	 *
	 * @param PHPMailer $mail
	 * @return bool|\WP_Error
	 * @throws \Exception
	 * @since 0.9.6
	 */
	private function test_credentials( $mail ) {
		
		try {
			$result = $mail->SmtpConnect();
			if(false === $result) {
				
				$error_message = '<strong>' . __( 'Could not authenticate.', $this->domain ) . '<br>' . __( 'Please review your username and password.', $this->domain ) . '</strong>';
				
				return new WP_Error( 1, $error_message );
			}
			
			return true;
			
		} catch( Exception $error ) {
			$error_message = '<strong>' . __( 'Internal Error: Could not check authentication.', $this->domain ) . '<br>' . __( 'Please try again later.', $this->domain ) . '</strong>';
			
			return new WP_Error( 1, $error_message );
		}
	}
	
	/**
	 * Checks if the PHP IMAP extension is loaded.
	 *
	 * @return bool|\WP_Error
	 * @since 1.0.0
	 */
	private function is_imap_extension_loaded() {
		
		$error_message  = '<strong>' . __( 'PHP IMAP extension is missing.', $this->domain ) . '</strong><br>' . __( 'Bonaire needs this extension to be installed and loaded in order to handle IMAP events. For local development, see for example: ', $this->domain );
		$read_more_link = '<a href="https://stackoverflow.com/questions/9654453/fatal-error-call-to-undefined-function-imap-open-in-php" target="_blank">Fatal error: Call to undefined function imap_open() in PHP</a>';
		
		$error_string = $error_message . ' ' . $read_more_link . '<br>' . __( 'For live websites, contact your admin or host in order to include this PHP extension.', $this->domain );
		
		return extension_loaded( "imap" ) ? true : new WP_Error( 2, $error_string );
	}
	
	/**
	 * Checks if SSL is enabled.
	 *
	 * @return bool|WP_Error
	 * @since 1.0.0
	 */
	public function is_ssl() {
		
		try{
			if ( isset( $_SERVER['HTTPS'] ) ) {
				if ( 'on' == strtolower( $_SERVER['HTTPS'] ) ) {
					return true;
				}
				if ( '1' == $_SERVER['HTTPS'] ) {
					return true;
				}
			} elseif ( isset( $_SERVER['SERVER_PORT'] ) && ( '443' == $_SERVER['SERVER_PORT'] ) ) {
				return true;
			}
			
			return new WP_Error( - 31, __( 'You need to install a SSL certificate, or set the value for "use certification validation to "nocert" (read it\'s tooltip and use the "nocert" option during local development only).', $this->domain ), 'orange' );
		} catch(Exception $e) {
			
			return new WP_Error( - 31, __( 'You need to install a SSL certificate, or set the value for "use certification validation to "nocert" (read it\'s tooltip and use the "nocert" option during local development only).', $this->domain ), 'orange' );
		}
		
	}
	
	/**
	 * Resloves the IMAP host.
	 *
	 * @param string $imap_host
	 *
	 * @return bool|\WP_Error
	 * @since 0.9.6
	 */
	private function resolve_imap_hostname( $imap_host ) {
		
		$protocol = 'IMAP';
		
		try {
			$test_dns = gethostbyname( $imap_host . '.' );
			
			if ( ! preg_match( '/\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/', $test_dns ) ) {
				$error_message = '<strong>' . wp_sprintf( __( 'Failed to resolve %1$s host name (%2$s).', $this->domain ), $protocol, $imap_host ) . '</strong><br>' . __( 'Please review your settings and run the test again.', $this->domain );
				
				return new WP_Error( 1, $error_message );
			}
		} catch( Exception $e ) {
			$error_message = '<strong>' . wp_sprintf( __( 'Internal Error: Unable to resolve %1$s host name (%2$s).', $this->domain ), $protocol, $imap_host ) . '</strong><br>' . __( 'Please try again later.', $this->domain );
			
			return new WP_Error( 2, $error_message );
		}
		
		return true;
	}
	
	/**
	 * Tests the IMAP port.
	 *
	 * @param string $smtp_host
	 * @param array $smtp_ports
	 *
	 * @return bool|\WP_Error
	 * @since 0.9.6 .
	 */
	private function test_imap_port( $smtp_host, $smtp_ports ) {
		
		try {
			
			if ( $socket = fsockopen( $smtp_host, $smtp_ports[0], $errno, $errstr, 2 ) ) {
				fclose( $socket );
				flush();
				$result = true;
			} else {
				flush();
				$error_message = '<strong>' . __( 'Failed to evaluate port number.', $this->domain ) . '</strong><br>' . wp_sprintf( __( 'Please review the port number of your IMAP server (%1$s).', $this->domain ), $errstr );
				$result        = new WP_Error( 1, $error_message );
			}
			unset( $socket );
		} catch( Exception $error ) {
			$error_message = __( 'Internal Error: Unable to check IMAP port.', $this->domain ) . '<br>' . __( 'Please try again later.', $this->domain );
			
			return new WP_Error( 2, $error_message );
		}
		
		return $result;
	}
	
	/**
	 * Tests wether the inbox is reachable or not and returns true on success or
	 * it returns an error.
	 *
	 * @param PHPMailer $mail
	 * @return bool|\WP_Error
	 * @since 0.9.6
	 */
	private function test_inbox($mail) {
		
		$folder_name = $this->stored_options->inbox_folder_name;
		$folder_path = $this->stored_options->inbox_folder_path;
		if(1 === $this->is_gmail() && '' === $folder_name && '' === $folder_path) {
			$message = __( 'Please specify the name of your Sent Items Folder.', $this->domain ) . ' ' . __( 'This would be "Sent" in the language you are using your Gmail Account with.', $this->domain ) . ' ' . __( 'Note that the name is case-sensitive.', $this->domain );
			
			return new WP_Error( 2, $message );
		}
		
		// Check for SSL
		if ( 'nocert' !== $this->stored_options->ssl_certification_validation && false === $this->is_ssl() ) {
			$error_message = __( 'Error: No SSL Certificate installed on this website.<br>During local website development, use the \'nocert\' option.<br>If you are on a live website, consider installing a SSL certificate and then use the \'cert\' option. Otherwise, you\'re a possible subject of man in the middle attacks', $this->domain ) . '<br>' . __( 'Please review your settings and run the test again.', $this->domain );
			$read_morelink = wp_sprintf( '<a href="https://stackoverflow.com/questions/7891729/certificate-error-using-imap-in-php" target="_blank">%1$d</a>)', __( 'Read more', $this->domain ) );
			$error_string = $error_message . '(' . $read_morelink . ')';
			
			return new WP_Error( 1, esc_html($error_string) );
		}
		
		try {
			$ssl_certification_validation = 'nocert' === $this->stored_options->ssl_certification_validation ? '/novalidate-cert' : '';
			$mailbox = $this->get_mailbox( $mail, $ssl_certification_validation, true, false );
			// Check IMAP connection
			$imapStream = imap_open( $mailbox, $mail->Username, $mail->Password ) or false;
			// Retrieve folder list
			$list = imap_list( $imapStream, '{' . $this->stored_options->imap_host . '}', '*' );
			// Check Sent Items Folder Path
			$path = $this->get_sent_items_folder_path_for_testing( $mail );
			if(false !== $imapStream && in_array( $path, $list, true ) ){
				// Close connection
				imap_close( $imapStream );
				
				return true;
			}

			$option = '' === $folder_path ? __('Sent Items Folder', $this->domain) : __( 'Sent Items Path', $this->domain );
			$error_message = wp_sprintf( __( 'Unable to access Sent Items Folder. Please review your input for %1$s and save the settings.', $this->domain ), $option ) . ' ' . __( 'Repeat the test if the status indicator didn\'t turn green.', $this->domain );
			
			return new WP_Error( 1, $error_message );

		} catch( Exception $e ) {
			
			return new WP_Error( 2, __( 'Internal Error: Unable to search for inbox folder.', $this->domain ) . '<br>' . __( 'Please try again later.', $this->domain ) );
		}

	}
	
	/**
	 * Returns the path to the mailbox on the mail server.
	 *
	 * @param PHPMailer $mail
	 * @param string $ssl_certification_validation
	 * @param bool $is_imap
	 * @param bool $recheck
	 *
	 * @return string
	 */
	private function get_mailbox( $mail, $ssl_certification_validation, $is_imap = false, $recheck = false ) {
		
		$mail->Host        = $this->stored_options->imap_host;
		$mail->Port        = $this->stored_options->imap_port;
		$secure            = true === $is_imap ? $this->stored_options->imapsecure : $this->stored_options->smtpsecure;
		$smtpsecure        = true === $recheck ? 'ssl' === $this->stored_options->imapsecure ? 'tls' : 'ssl' : $secure;

		return '{' . $mail->Host . ':' . $mail->Port . '/imap/' . $smtpsecure . $ssl_certification_validation . '}INBOX';
	}
	
	/**
	 * @param PHPMailer $mail
	 *
	 * @return string
	 */
	private function get_sent_items_folder_path_for_testing( $mail ) {
		
		if ( $this->is_gmail() && '' !== $this->stored_options->inbox_folder_path ) {
			
			return $this->stored_options->inbox_folder_path;
		}
		
		return $this->get_sent_items_folder_for_send_mail( $mail );
	}
	
	/**
	 * Returns the path to the user's Sent Items folder.
	 *
	 * @param PHPMailer $mail
	 *
	 * @return string
	 */
	private function get_sent_items_folder_for_send_mail( $mail ) {
		
		$inbox = $this->is_gmail() ? "[Gmail]/" : "INBOX.";
		
		$inbox_folder_name = $this->is_gmail() && '' !== $this->stored_options->inbox_folder_name ? $this->stored_options->inbox_folder_name : 'Sent';
		
		return '{' . $mail->Host . '}' . $inbox . $inbox_folder_name;
	}
	
	/**
	 * Checks if the account in use is gmail.
	 *
	 * @return int|false
	 * @since 1.0.0
	 */
	private function is_gmail() {
		
		return preg_match( '/smtp.gmail.com/', $this->stored_options->smtp_host );
	}
	
}
